"""create movers table

Revision ID: 2b797757badf
Revises: 3271525bdcde
Create Date: 2026-08-30 16:15:21.820834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b797757badf'
down_revision = '3271525bdcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('service_area', sa.String(length=150), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('vehicle_capacity', sa.Float(), nullable=True),
    sa.Column('price_per_km', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movers_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movers_user_id'))

    op.drop_table('movers')
    # ### end Alembic commands ###
