"""add tracking items

Revision ID: dd5ec7f9e34c
Revises: e46b8c0d3a71
Create Date: 2026-08-30 06:42:38.004161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ec7f9e34c'
down_revision = 'e46b8c0d3a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_items_booking_id'), ['booking_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_items_booking_id'))

    op.drop_table('tracking_items')
    # ### end Alembic commands ###
